"""tap-7726 events belong to a host

Adds `events.host_id`, backfills it, then makes it NOT NULL.

The backfill is the interesting part, because the column has to end up NOT NULL and
this migration may meet a database that already has events but no hosts — exactly the
state every deployment is in right now, since TAP-7725 created the `hosts` table only
one revision ago and nobody has registered.

So: existing events are given to the oldest host if there is one. If there is not, a
placeholder host is created to own them. Its password hash is a literal that argon2
cannot parse, so verification always fails and nobody can sign in as it — the events
are preserved and unreachable, rather than deleted or handed to whoever registers
first. `scripts/adopt_events.py` moves them to a real host afterwards.

Written by hand rather than autogenerated: `--autogenerate` produces the ALTER without
the backfill, which fails on any non-empty table.

Revision ID: e1af5f443223
Revises: cc20600801c7
Create Date: 2026-09-16 21:40:11.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1af5f443223"
down_revision: str | Sequence[str] | None = "cc20600801c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Marks the row this migration invented, so the downgrade can take it away again and
# `scripts/adopt_events.py` can recognize it.
PLACEHOLDER_EMAIL = "unassigned@invalid.localhost"

# Not a valid argon2 digest, so `PasswordHasher.verify` raises InvalidHashError and
# `app.auth.verify_password` returns False. There is no password that opens this row.
UNUSABLE_PASSWORD = "!no-login-tap-7726"


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("events", sa.Column("host_id", sa.UUID(), nullable=True))

    connection = op.get_bind()
    orphans = connection.execute(
        sa.text("SELECT count(*) FROM events WHERE host_id IS NULL")
    ).scalar_one()

    if orphans:
        owner = connection.execute(
            sa.text("SELECT id FROM hosts ORDER BY created_at, id LIMIT 1")
        ).scalar()
        if owner is None:
            owner = connection.execute(
                sa.text(
                    "INSERT INTO hosts (id, email, password_hash) "
                    "VALUES (gen_random_uuid(), :email, :digest) RETURNING id"
                ),
                {"email": PLACEHOLDER_EMAIL, "digest": UNUSABLE_PASSWORD},
            ).scalar_one()
        connection.execute(
            sa.text("UPDATE events SET host_id = :owner WHERE host_id IS NULL"),
            {"owner": owner},
        )

    op.alter_column("events", "host_id", nullable=False)
    op.create_index(op.f("ix_events_host_id"), "events", ["host_id"])
    op.create_foreign_key(
        "fk_events_host_id_hosts", "events", "hosts", ["host_id"], ["id"], ondelete="RESTRICT"
    )


def downgrade() -> None:
    """Downgrade schema.

    The placeholder host goes too, but only if this migration created it and nothing
    else came to depend on it. A host somebody actually registered is left alone.
    """
    op.drop_constraint("fk_events_host_id_hosts", "events", type_="foreignkey")
    op.drop_index(op.f("ix_events_host_id"), table_name="events")
    op.drop_column("events", "host_id")

    op.get_bind().execute(
        sa.text(
            "DELETE FROM hosts WHERE email = :email AND password_hash = :digest "
            "AND NOT EXISTS (SELECT 1 FROM host_sessions WHERE host_sessions.host_id = hosts.id)"
        ),
        {"email": PLACEHOLDER_EMAIL, "digest": UNUSABLE_PASSWORD},
    )
